### ISSUE TITLE
联通阅读失败

### ISSUE THREAD

**Issue by johnzon520** [iptag/checkin#10]
## 开始执行... 2024-12-09 17:24:05

xxxxxxxxxxxx
尝试检查运行环境...
成功，当前环境为 Linux。
环境检查结束。

配置文件 (check.toml) 检查开始...
在 check.toml 发现配置文件。
配置文件检查结束。

手机号登录失败, 日志为{'code': '9999', 'message': '非法的参数', 'innercode': '6666'}

## 执行结束... 2024-12-09 17:24:06  耗时 1 秒　　　　　

appid 账户密码都确认填写正确，麻烦大佬有空看下，谢谢。

**Comment by iptag** [comment]
这是好老的脚本了，暂时没空维护
